# Site settings
title: vitto
email: me@vit.to
description: > # this means to ignore newlines until "baseurl:"
    vit.to is the personal homepage of Vittorio Vittori,
    a front-end developer who works at ideato srl,
    an italian company which builds awesome websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
theme: "/img/theme/"
twitter_username: vttrx
github_username:  vitto

# Build settings
markdown: kramdown
exclude: [ README.md, frontsize-less, frontsize-sass, test, css/empty, fonts/empty, img/empty ]
timezone: Europe/Rome
keep_files: [ css, fonts, img ]
