# Site settings
title: vitto
email: me@vit.to
description: > # this means to ignore newlines until "baseurl:"
    vit.to is the personal homepage of Vittorio Vittori,
    a front-end developer who works at ideato srl,
    an italian company which builds awesome websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vit.to" # the base hostname & protocol for your site
twitter_username: vttrx
github_username:  vitto

# Build settings
markdown: kramdown
exclude: [ frontsize ]
