source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Site settings
title:          vitto
email:          me@vit.to
description:    "vit.to is the personal homepage of Vittorio Vittori, a front-end developer who works at ideato srl, an italian company which builds awesome websites."
baseurl:        ""
url:            "http://0.0.0.0:4000" # the base hostname & protocol for your site
theme:          "/img/theme/"
twitter_user:   vttrx
github_user:    vitto
social_preview: http://vit.to/img/theme/social-preview.jpg
paginate:       2
paginate_path:  "/blog/page-:num/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:    [ bin, Gemfile, Gruntfile.js, frontsize.json, package.json, README.md, frontsize-sass, test, css/empty, fonts/empty, img/empty, node_modules, .sass-cache ]
timezone:   Europe/Rome
keep_files: [ css, fonts, img ]

